/**
 * Site configuration — edit this file when adding projects or changing the home page.
 *
 * To make a new project the homepage: set `homePage` to that project's `page` filename.
 * To add a project: add an entry to `projects`, create a new HTML file from any project template.
 *
 * Per image (gallery caption, Figma 131:3815):
 * - `title` — Director; `size`, `medium`, `year` — KMR Waldenburg (16px gaps)
 * - `showInGrid: false` — hidden in grid only (still in gallery).
 * - `galleryFit: "fit"` — full image in gallery; omit or `"fill"` — crop (default).
 *
 * Per project: `showGridView: false` — gallery only (hides Gallery/Grid toggle).
 */
const SITE_CONFIG = {
  homePage: "MANA_2026.html",
  cvFile: "assets/CV.pdf",
  exhibitionTextPage: "exhibition-text-lake-house.html",

  projects: [
    {
      id: "mana-2026",
      year: "2026",
      title: "MANA",
      page: "MANA_2026.html",
      imageDir: "../Paintings/MANA-2026/",
      images: [
        {
          file: "1.png",
          title: "War and War",
          size: "48x60 inches",
          medium: "oil on canvas",
          year: "2026",
        },
        {
          file: "2.png",
          title: "Tower",
          size: "27x17 inches",
          medium: "oil on canvas",
          year: "2026",
        },
        {
          file: "3.jpg",
          title: "Rococo",
          size: "40x30 inches",
          medium: "oil on canvas",
          year: "2026",
        },
        {
          file: "4.jpg",
          title: "Saturn",
          size: "13x17 inches",
          medium: "oil on canvas",
          year: "2026",
        },
        {
          file: "5.jpg",
          title: "William's Glass II",
          size: "12x16 inches",
          medium: "oil on canvas",
          year: "2026",
        },
        {
          file: "6.jpg",
          title: "William's Glass III",
          size: "12x16 inches",
          medium: "oil on canvas",
          year: "2026",
        },
        {
          file: "7.jpg",
          title: "Graduation",
          size: "54x66 inches",
          medium: "oil on canvas",
          year: "2026",
        }
      ],
    },
    {
      id: "specimens-2026",
      year: "2026",
      title: "Specimens",
      page: "Specimens_2026.html",
      imageDir: "../Paintings/Specimens-2026/",
      images: [
        {
          file: "1.jpg",
          title: "Father, Father",
          size: "18x13 inches",
          medium: "oil on canvas",
          year: "2026",
          galleryFit: "fit",
        },
        {
          file: "2.jpg",
          title: "Big Fat Dumplings",
          size: "12x16 inches",
          medium: "oil on canvas",
          year: "2026",
          galleryFit: "fit",
        },
        {
          file: "3.jpg",
          title: "Rose Garden",
          size: "12x16 inches",
          medium: "oil on canvas",
          year: "2026",
          galleryFit: "fit",
        },
        {
          file: "4.jpg",
          title: "Specimens",
          medium: "Installation View",
          year: "2026",
          showInGrid: false,
        },
        {
          file: "5.jpg",
          title: "Specimens",
          medium: "Installation View",
          year: "2026",
          showInGrid: false,
        },
        {
          file: "6.jpg",
          title: "Specimens",
          medium: "Installation View",
          year: "2026",
          showInGrid: false,
        },  
        {
          file: "7.jpg",
          title: "Moth",
          size: "16x20 inches",
          medium: "oil on canvas",
          year: "2026",
          galleryFit: "fit",
        },
        {
          file: "8.jpg",
          title: "Pigeon",
          size: "34x26 inches",
          medium: "oil on canvas",
          year: "2025",
          galleryFit: "fit",
        },
        {
          file: "9.jpg",
          title: "Edge",
          size: "12x9 inches",
          medium: "oil on canvas",
          year: "2026",
          galleryFit: "fit",
        },
        {
          file: "10.jpg",
          title: "Specimens",
          medium: "Installation View",
          year: "2026",
          showInGrid: false,
        }
      ],
    },
    {
      id: "nars-foundation-2025",
      year: "2025",
      title: "NARS Foundation",
      page: "NARS-Foundation_2025.html",
      imageDir: "../Paintings/NARS-Foundation-2025/",
      images: [
        {
          file: "1.jpg",
          title: "Willow",
          size: "48x36 inches",
          medium: "oil on canvas",
          year: "2025",
          galleryFit: "fill",
        },
        {
          file: "2.jpg",
          title: "Drive My Car",
          size: "34x26 inches",
          medium: "oil on canvas",
          year: "2025",
          galleryFit: "fill",
        },
        {
          file: "3.jpg",
          title: "Fountain",
          size: "26x20 inches",
          medium: "oil on canvas",
          year: "2025",
          galleryFit: "fill",
        },
        {
          file: "4.jpg",
          title: "Dome",
          size: "60x48 inches",
          medium: "oil on canvas",
          year: "2025",
          galleryFit: "fill",
        },
        {
          file: "5.jpg",
          title: "Aquarium",
          size: "30x40 inches",
          medium: "oil on canvas",
          year: "2025",
          galleryFit: "fill",
        },
        {
          file: "6.jpg",
          title: "Apprentice",
          size: "30x40 inches",
          medium: "oil on canvas",
          year: "2025",
          galleryFit: "fill",
        },
        {
          file: "7.jpg",
          title: "Chest is a Precise Instrument",
          size: "54x66 inches",
          medium: "oil on canvas",
          year: "2025",
          galleryFit: "fill",
        },
        {
          file: "8.jpg",
          title: "Untitled",
          size: "48x36 inches",
          medium: "oil on canvas",
          year: "2025",
          galleryFit: "fill",
        },
        {
          file: "9.jpg",
          title: "Cross Crossings to Cross",
          medium: "installation view",
          year: "2025",
          showInGrid: false,
        },
      
      ],
    },
    {
      id: "lake-house-2024",
      year: "2024",
      title: "Lake House",
      page: "Lake-House_2024.html",
      imageDir: "../Paintings/Lake-House-2024/",
      images: [
        {
          file: "1.jpg",
          title: "Dusk",
          size: "36×30.5 inch",
          medium: "oil on canvas",
          year: "2023",
          galleryFit: "fit",
        },
        {
          file: "2.jpg",
          title: "Cabin by the Pond",
          size: "26×20 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "3.jpg",
          title: "Old Fashioned",
          size: "48×36 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "4.jpg",
          title: "Supersonic Highway",
          size: "26×34 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "5.jpg",
          title: "Midsummer Romancee",
          size: "26×34 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "6.jpg",
          title: "Wrinkled Denim",
          size: "26×20 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "7.jpg",
          title: "Bullseye",
          size: "13×17 inch",
          medium: "oil on canvas",
          year: "2023",
          galleryFit: "fit",
        },
        {
          file: "8.jpg",
          title: "Olive Salad",
          size: "12×9 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "9.jpg",
          title: "Can't Stand the Rain",
          size: "48×38 inch",
          medium: "oil on canvas",
          year: "2023",
          galleryFit: "fit",
        },
        {
          file: "10.jpg",
          title: "Miller's Love",
          size: "26×20 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "11.jpg",
          title: "Dionysus",
          size: "12×16 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "12.jpg",
          title: "In Unison",
          size: "48×36 inch",
          medium: "oil on canvas",
          year: "2023",
          galleryFit: "fit",
        },
        {
          file: "13.jpg",
          title: "Skin and Bones",
          size: "48×36 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "14.jpg",
          title: "Mountain Snow",
          size: "54×38 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "15.jpg",
          title: "Cobweb",
          size: "26×34 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "16.jpg",
          title: "Swallow",
          size: "17×10 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "17.jpg",
          title: "William's Glass I",
          size: "12x16 inches",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "18.jpg",
          title: "Orchestra",
          size: "12×16 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "19.jpg",
          title: "Silver Platter",
          size: "12×16 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "20.jpg",
          title: "Sinking In",
          size: "12×16 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "21.jpg",
          title: "Asian American Household",
          size: "12×16 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "22.jpg",
          title: "Postcard",
          size: "12×16 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "23.jpg",
          title: "Hill House",
          size: "12×9 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "24.jpg",
          title: "Rising like Loaves",
          size: "12×9 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "25.jpg",
          title: "Over Lake Michigan",
          size: "12×9 inch",
          medium: "oil on canvas",
          year: "2024",
          galleryFit: "fit",
        },
        {
          file: "26.jpg",
          title: "Lake House",
          size: "",
          medium: "Installation View",
          year: "2024",
          showInGrid: false,
        },
        {
          file: "27.jpg",
          title: "Lake House",
          size: "",
          medium: "Installation View",
          year: "2024",
          showInGrid: false,
        },
        {
          file: "28.jpg",
          title: "Lake House",
          size: "",
          medium: "Installation View",
          year: "2024",
          showInGrid: false,
        },
        {
          file: "29.jpg",
          title: "Lake House",
          size: "",
          medium: "Installation View",
          year: "2024",
          showInGrid: false,
        },
        {
          file: "30.jpg",
          title: "Lake House",
          size: "",
          medium: "Installation View",
          year: "2024",
          showInGrid: false,
        },
        {
          file: "31.jpg",
          title: "Lake House",
          size: "",
          medium: "Installation View",
          year: "2024",
          showInGrid: false,
        },
        {
          file: "32.jpg",
          title: "Lake House",
          size: "",
          medium: "Installation View",
          year: "2024",
          showInGrid: false,
        },
        {
          file: "33.jpg",
          title: "Lake House",
          size: "",
          medium: "Installation View",
          year: "2024",
          showInGrid: false,
        },
        {
          file: "34.jpg",
          title: "Lake House",
          size: "",
          medium: "Installation View",
          year: "2024",
          showInGrid: false,
        },
        {
          file: "35.jpg",
          title: "Lake House",
          size: "",
          medium: "Installation View",
          year: "2024",
          showInGrid: false,
        }
      ],
    },
    {
      id: "norfolk-2023",
      year: "2023",
      title: "Norfolk",
      page: "Norfolk_2023.html",
      imageDir: "../Paintings/Norfolk-2023/",
      showGridView: false,
      images: [
        {
          file: "1.jpeg",
          title: "Untitled",
          size: "12x16 inches",
          medium: "oil on canvas",
          year: "2023",
          galleryFit: "fit",
        },
        {
          file: "2.jpeg",
          title: "Off You Go",
          size: "12x9 inches each",
          medium: "paper transfer on canvas",
          year: "2023",
          galleryFit: "fit",
        },
        {
          file: "3.jpg",
          title: "Untitled",
          size: "9x12 inches",
          medium: "oil on canvas",
          year: "2023",
          galleryFit: "fit",
        },
        {
          file: "4.jpg",
          title: "Blue/Green",
          size: "36x72",
          medium: "",
          year: "2023",
          galleryFit: "fit",
        },
        {
          file: "5.jpg",
          title: "Knife Out",
          size: "18x30 inches",
          medium: "oil on canvas",
          year: "2023",
          galleryFit: "fit",
        },
        {
          file: "6.jpg",
          title: "Untitled",
          size: "30x20 inches",
          medium: "oil on canvas",
          year: "2023",
          galleryFit: "fit",
        },
        {
          file: "7.jpeg",
          title: "Untitled",
          size: "42x30 inches",
          medium: "inkjet print",
          year: "2023",
          galleryFit: "fit",
        },
        {
          file: "8.jpg",
          title: "Last Drop of Night",
          size: "9x9 inches",
          medium: "oil on canvas",
          year: "2023",
          galleryFit: "fit",
        }
      ],
    },
  ],

  aboutPage: "about_2023.html",
};
